version: "1.0"

services:
    alpine-3:
        container_name: alpine-3
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
          - "8000:8000"
          - "5173:5173"
          - "9005:9005"
        volumes:
          - ./apps:/var/www/html
        networks:
            - application
        restart: unless-stopped
        stdin_open: true
        tty: true  
    postgres-15:
        image: postgres:15
        env_file: "posgres.env"
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
        networks:
            - application
        container_name: postgres-15
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
networks:
    application:
        driver: bridge

